languages:
  JavaScript: true
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      max-statements:
        enabled: false
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    checks:
      Similar code:
        enabled: false
